

// SPDX-License-Identifier: GPL-2.0
#include <kunit/test.h>
#include <linux/platform_device.h>
#include <linux/io.h>
#include <linux/err.h>
#include <linux/gpio/driver.h>
#include <linux/acpi.h>
#include <linux/module.h>
#include <linux/slab.h>

/* ----------------------------------------------------------------------- */
/* Test fixtures and controllable stubs                                     */
/* ----------------------------------------------------------------------- */

static struct platform_device test_pdev;
static struct device test_dev;

/* ioremap result we want to force */
static void *test_reg_base_ptr;

/* return code we want bgpio_init to produce */
static int test_bgpio_ret;

/* a stable "private" buffer returned by devm_kzalloc and via gpiochip_get_data */
static u8 fake_priv[256];

/* a dummy "mapped" MMIO area for success path */
static char test_mmio_buffer[64];

/* any non-NULL to represent an ACPI companion */
static struct acpi_device dummy_acpi;

/* ---- Overrides visible to the driver below ---- */

#undef ACPI_COMPANION
#define ACPI_COMPANION(dev) ((dev)->platform_data)

#undef devm_platform_ioremap_resource
#define devm_platform_ioremap_resource(_pdev, _index) (test_reg_base_ptr)

#undef devm_kzalloc
#define devm_kzalloc(_dev, _size, _gfp) ((void *)fake_priv)

#undef gpiochip_get_data
static inline void *pt_gpiochip_get_data(struct gpio_chip *gc)
{
    return (void *)fake_priv;
}
#define gpiochip_get_data(gc) pt_gpiochip_get_data(gc)

/* Map bgpio_init to our controllable stub */
#define bgpio_init(...) pt_test_bgpio_init(__VA_ARGS__)
static int pt_test_bgpio_init(...) { return test_bgpio_ret; }

/* ----------------------------------------------------------------------- */
/* Include the real driver ONCE (after stubs)                               */
/* ----------------------------------------------------------------------- */

#include "gpio-amdpt.c"   /* <<< Ensure this appears only once in this file */

/* ----------------------------------------------------------------------- */
/* Tests                                                                    */
/* ----------------------------------------------------------------------- */

static void test_pt_gpio_probe_acpi_missing(struct kunit *test)
{
    /* No ACPI companion -> expect -ENODEV and the error log */
    test_dev.platform_data = NULL;
    test_pdev.dev = test_dev;

    test_reg_base_ptr = (void *)test_mmio_buffer; /* safe default */
    test_bgpio_ret = 0;

    KUNIT_EXPECT_EQ(test, pt_gpio_probe(&test_pdev), -ENODEV);
}

static void test_pt_gpio_probe_mmio_fail(struct kunit *test)
{
    /* ACPI present, but ioremap fails -> ERR_PTR(-EIO) */
    test_dev.platform_data = &dummy_acpi;
    test_pdev.dev = test_dev;

    test_reg_base_ptr = ERR_PTR(-EIO);
    test_bgpio_ret = 0;

    KUNIT_EXPECT_EQ(test, pt_gpio_probe(&test_pdev), -EIO);
}

static void test_pt_gpio_probe_bgpio_fail(struct kunit *test)
{
    /* ACPI present, ioremap OK, but bgpio_init fails -> -EINVAL */
    test_dev.platform_data = &dummy_acpi;
    test_pdev.dev = test_dev;

    test_reg_base_ptr = (void *)test_mmio_buffer;
    test_bgpio_ret = -EINVAL;

    KUNIT_EXPECT_EQ(test, pt_gpio_probe(&test_pdev), -EINVAL);
}

static void test_pt_gpio_probe_success(struct kunit *test)
{
    /* ACPI present, ioremap OK, bgpio_init OK -> success (0) */
    test_dev.platform_data = &dummy_acpi;
    test_pdev.dev = test_dev;

    test_reg_base_ptr = (void *)test_mmio_buffer;
    test_bgpio_ret = 0;

    KUNIT_EXPECT_EQ(test, pt_gpio_probe(&test_pdev), 0);
}

/* If you want to exercise the driver's exit symbol generated by module_platform_driver: */
extern void pt_gpio_driver_exit(void);
static void exit_driver_test(struct kunit *test)
{
    pt_gpio_driver_exit();
    KUNIT_EXPECT_EQ(test, 0, 0);
}

static struct kunit_case pt_gpio_test_cases[] = {
    KUNIT_CASE(test_pt_gpio_probe_acpi_missing),
    KUNIT_CASE(test_pt_gpio_probe_mmio_fail),
    KUNIT_CASE(test_pt_gpio_probe_bgpio_fail),
    KUNIT_CASE(test_pt_gpio_probe_success),
    KUNIT_CASE(exit_driver_test),
    {}
};

static struct kunit_suite pt_gpio_test_suite = {
    .name = "pt_gpio_test",
    .test_cases = pt_gpio_test_cases,
};

kunit_test_suite(pt_gpio_test_suite);

MODULE_LICENSE("GPL");
MODULE_AUTHOR("You");
MODULE_DESCRIPTION("KUnit tests for AMD PT GPIO probe using stubs");

